export type GameConfig = {
  id: string;
  name: string;
  shortName: string;
  roles: string[];
  ranks: string[];
};

export const GAMES_CONFIG: Record<string, GameConfig> = {
  VALORANT: {
    id: "VALORANT",
    name: "VALORANT",
    shortName: "VAL",
    roles: ["DUELIST", "INITIATOR", "CONTROLLER", "SENTINEL", "IGL", "FLEX", "SUB", "COACH", "ANALYST"],
    ranks: [
      "Radiant",
      "Immortal 3",
      "Immortal 2",
      "Immortal 1",
      "Ascendant 3",
      "Ascendant 2",
      "Ascendant 1",
      "Diamond 3",
      "Diamond 2",
      "Diamond 1",
      "Platinum 3",
      "Platinum 2",
      "Platinum 1",
      "Gold 3",
      "Gold 2",
      "Gold 1",
      "Silver 3",
      "Silver 2",
      "Silver 1",
      "Bronze 3",
      "Bronze 2",
      "Bronze 1",
      "Iron 3",
      "Iron 2",
      "Iron 1",
    ],
  },
  CS2: {
    id: "CS2",
    name: "COUNTER-STRIKE 2",
    shortName: "CS2",
    roles: [
      "IGL (In-Game Leader)",
      "AWPER (Sniper)",
      "ENTRY FRAGGER",
      "RIFLER",
      "LURKER",
      "SUPPORT",
      "ANCHOR",
      "COACH",
      "SUBSTITUTE",
    ],
    ranks: [
      "Premier: 30,000+ ELO (World Elite)",
      "Premier: 25,000 - 29,999 ELO",
      "Premier: 20,000 - 24,999 ELO",
      "Premier: 15,000 - 19,999 ELO",
      "Premier: 10,000 - 14,999 ELO",
      "Premier: 5,000 - 9,999 ELO",
      "FACEIT Level 10 (Challenger)",
      "FACEIT Level 9",
      "FACEIT Level 8",
      "The Global Elite",
      "Supreme Master First Class",
      "Legendary Eagle Master",
      "Legendary Eagle",
      "Distinguished Master Guardian",
      "Master Guardian Elite",
      "Master Guardian II",
      "Master Guardian I",
      "Gold Nova Master",
      "Gold Nova III",
      "Gold Nova II",
      "Gold Nova I",
      "Silver Elite Master",
      "Silver Elite",
      "Silver IV",
      "Silver III",
      "Silver II",
      "Silver I",
    ],
  },
  "LEAGUE OF LEGENDS": {
    id: "LEAGUE OF LEGENDS",
    name: "LEAGUE OF LEGENDS",
    shortName: "LOL",
    roles: [
      "TOP LANER",
      "JUNGLER",
      "MID LANER",
      "BOT / ADC (Carry)",
      "SUPPORT",
      "SHOTCALLER / IGL",
      "SUBSTITUTE",
      "HEAD COACH",
    ],
    ranks: [
      "Challenger",
      "Grandmaster",
      "Master",
      "Diamond I",
      "Diamond II",
      "Diamond III",
      "Diamond IV",
      "Emerald I",
      "Emerald II",
      "Emerald III",
      "Emerald IV",
      "Platinum I",
      "Platinum II",
      "Platinum III",
      "Platinum IV",
      "Gold I",
      "Gold II",
      "Gold III",
      "Gold IV",
      "Silver I",
      "Silver II",
      "Silver III",
      "Silver IV",
      "Bronze I",
      "Bronze II",
      "Bronze III",
      "Bronze IV",
      "Iron I",
      "Iron II",
      "Iron III",
      "Iron IV",
    ],
  },
  "DOTA 2": {
    id: "DOTA 2",
    name: "DOTA 2",
    shortName: "DOTA",
    roles: [
      "POSITION 1 (Safe Lane / Carry)",
      "POSITION 2 (Mid Lane)",
      "POSITION 3 (Offlane)",
      "POSITION 4 (Soft Support)",
      "POSITION 5 (Hard Support / Captain)",
      "COACH",
      "SUBSTITUTE",
    ],
    ranks: [
      "Immortal (Rank 1 - 100)",
      "Immortal (Top 500)",
      "Immortal (Top 1000)",
      "Immortal",
      "Divine 5",
      "Divine 4",
      "Divine 3",
      "Divine 2",
      "Divine 1",
      "Ancient 5",
      "Ancient 4",
      "Ancient 3",
      "Ancient 2",
      "Ancient 1",
      "Legend 5",
      "Legend 4",
      "Legend 3",
      "Legend 2",
      "Legend 1",
      "Archon 5",
      "Archon 4",
      "Archon 3",
      "Archon 2",
      "Archon 1",
      "Crusader 5",
      "Crusader 4",
      "Crusader 3",
      "Crusader 2",
      "Crusader 1",
      "Guardian 5",
      "Guardian 4",
      "Guardian 3",
      "Guardian 2",
      "Guardian 1",
      "Herald 5",
      "Herald 4",
      "Herald 3",
      "Herald 2",
      "Herald 1",
    ],
  },
  "APEX LEGENDS": {
    id: "APEX LEGENDS",
    name: "APEX LEGENDS",
    shortName: "APEX",
    roles: [
      "IGL / PRIMARY FRAGGER",
      "RECON / ENTRY",
      "ANCHOR / SUPPORT",
      "FLEX",
      "COACH",
    ],
    ranks: [
      "Apex Predator (Top 750)",
      "Master",
      "Diamond I",
      "Diamond II",
      "Diamond III",
      "Diamond IV",
      "Platinum I",
      "Platinum II",
      "Platinum III",
      "Platinum IV",
      "Gold I",
      "Gold II",
      "Gold III",
      "Gold IV",
      "Silver I",
      "Silver II",
      "Silver III",
      "Silver IV",
      "Bronze I",
      "Bronze II",
      "Bronze III",
      "Bronze IV",
      "Rookie I",
      "Rookie II",
      "Rookie III",
      "Rookie IV",
    ],
  },
  "OVERWATCH 2": {
    id: "OVERWATCH 2",
    name: "OVERWATCH 2",
    shortName: "OW2",
    roles: [
      "TANK (Main / Off)",
      "DAMAGE (Hitscan)",
      "DAMAGE (Flex / Projectile)",
      "MAIN SUPPORT",
      "FLEX SUPPORT",
      "IGL",
      "COACH",
    ],
    ranks: [
      "Top 500",
      "Champion 1",
      "Champion 2",
      "Champion 3",
      "Champion 4",
      "Champion 5",
      "Grandmaster 1",
      "Grandmaster 2",
      "Grandmaster 3",
      "Grandmaster 4",
      "Grandmaster 5",
      "Master 1",
      "Master 2",
      "Master 3",
      "Master 4",
      "Master 5",
      "Diamond 1",
      "Diamond 2",
      "Diamond 3",
      "Diamond 4",
      "Diamond 5",
      "Platinum 1",
      "Platinum 2",
      "Platinum 3",
      "Platinum 4",
      "Platinum 5",
      "Gold 1",
      "Gold 2",
      "Gold 3",
      "Gold 4",
      "Gold 5",
      "Silver 1",
      "Silver 2",
      "Silver 3",
      "Silver 4",
      "Silver 5",
      "Bronze 1",
      "Bronze 2",
      "Bronze 3",
      "Bronze 4",
      "Bronze 5",
    ],
  },
  "RAINBOW SIX": {
    id: "RAINBOW SIX",
    name: "RAINBOW SIX SIEGE",
    shortName: "R6",
    roles: [
      "ENTRY FRAGGER",
      "HARD BREACHER",
      "SUPPORT / FLANK WATCH",
      "ROAMER",
      "ANCHOR / SITE HOLDER",
      "IGL",
      "COACH",
    ],
    ranks: [
      "Champions (Top Global)",
      "Diamond I",
      "Diamond II",
      "Diamond III",
      "Diamond IV",
      "Diamond V",
      "Emerald I",
      "Emerald II",
      "Emerald III",
      "Emerald IV",
      "Emerald V",
      "Platinum I",
      "Platinum II",
      "Platinum III",
      "Gold I",
      "Gold II",
      "Gold III",
      "Silver I",
      "Silver II",
      "Silver III",
      "Bronze I",
      "Bronze II",
      "Bronze III",
      "Copper I",
      "Copper II",
      "Copper III",
    ],
  },
  "ROCKET LEAGUE": {
    id: "ROCKET LEAGUE",
    name: "ROCKET LEAGUE",
    shortName: "RL",
    roles: [
      "FIRST MAN (Striker)",
      "SECOND MAN (Midfield / Setup)",
      "THIRD MAN (Defense / Goalie)",
      "ROTATING FLEX",
      "COACH",
    ],
    ranks: [
      "Supersonic Legend (SSL)",
      "Grand Champion III",
      "Grand Champion II",
      "Grand Champion I",
      "Champion III",
      "Champion II",
      "Champion I",
      "Diamond III",
      "Diamond II",
      "Diamond I",
      "Platinum III",
      "Platinum II",
      "Platinum I",
      "Gold III",
      "Gold II",
      "Gold I",
      "Silver III",
      "Silver II",
      "Silver I",
      "Bronze III",
      "Bronze II",
      "Bronze I",
    ],
  },
  FORTNITE: {
    id: "FORTNITE",
    name: "FORTNITE",
    shortName: "FN",
    roles: [
      "IGL (Tarper / Rotator)",
      "FRAGGER",
      "SUPPORT",
      "SOLO OPERATOR",
    ],
    ranks: [
      "Unreal (#1 - Top 10,000)",
      "Champion",
      "Elite",
      "Diamond III",
      "Diamond II",
      "Diamond I",
      "Platinum III",
      "Platinum II",
      "Platinum I",
      "Gold III",
      "Gold II",
      "Gold I",
      "Silver III",
      "Silver II",
      "Silver I",
      "Bronze III",
      "Bronze II",
      "Bronze I",
    ],
  },
  "CALL OF DUTY": {
    id: "CALL OF DUTY",
    name: "CALL OF DUTY",
    shortName: "COD",
    roles: [
      "MAIN AR (Assault Rifle)",
      "SMG ENTRY",
      "SMG SLAYER",
      "FLEX AR/SMG",
      "SNIPER (SND)",
      "IGL",
      "COACH",
    ],
    ranks: [
      "Top 250 (Iridescent Elite)",
      "Iridescent",
      "Crimson III",
      "Crimson II",
      "Crimson I",
      "Diamond III",
      "Diamond II",
      "Diamond I",
      "Platinum III",
      "Platinum II",
      "Platinum I",
      "Gold III",
      "Gold II",
      "Gold I",
      "Silver III",
      "Silver II",
      "Silver I",
      "Bronze III",
      "Bronze II",
      "Bronze I",
    ],
  },
  OTHER: {
    id: "OTHER",
    name: "OTHER / GENERAL",
    shortName: "GEN",
    roles: [
      "CAPTAIN / IGL",
      "STARTER",
      "SNIPER / FRAGGER",
      "SUPPORT",
      "FLEX",
      "SUBSTITUTE",
      "HEAD COACH",
      "ANALYST",
      "TEAM MANAGER",
    ],
    ranks: [
      "Rank 1 / Global Champion",
      "Pro / Master Tier",
      "Tier 1 Competitive",
      "Diamond / Advanced",
      "Gold / Intermediate",
      "Amateur / Contender",
    ],
  },
};

export const GAME_LIST = Object.keys(GAMES_CONFIG);

export function getGameConfig(gameName?: string): GameConfig {
  if (!gameName) return GAMES_CONFIG.VALORANT;
  const key = gameName.toUpperCase().trim();
  return GAMES_CONFIG[key] || {
    id: key,
    name: gameName,
    shortName: key.slice(0, 3),
    roles: GAMES_CONFIG.OTHER.roles,
    ranks: GAMES_CONFIG.OTHER.ranks,
  };
}
